### PR TITLE
Fix cross-reference links and updated packages list

### PR DESCRIPTION
**Pull request by yukaizou2015**
Updated cross-reference links for some sections and figures. Also updated necessary packages that have been archived in CRAN.

### CODE REVIEW

**Comment by poldrack** [comment]
many thanks!

**Comment by poldrack** [comment]
note that the circleci automated build failed so your changes have not shown up in the rendered document. I should set up rendering using Github Actions but not sure when I can get around to that - in the meantime I will try to build it locally and push

**Comment by yukaizou2015** [comment]
> note that the circleci automated build failed so your changes have not shown up in the rendered document. I should set up rendering using Github Actions but not sure when I can get around to that - in the meantime I will try to build it locally and push

It seems that the build failed due to a permission issue. I'm not entirely sure about the cause, but [this post](https://discuss.circleci.com/t/git-github-com-permission-denied-publickey-on-repo-that-previously-worked/37763/3) might offer some hints on how to address it.

**Comment by poldrack** [comment]
thanks! got that fixed, but now there is an issue with the book actually compiling. I am going to update the docker container (which is way outdated at this point) to see if I can fix the problem.

**Pull request merged**
